name: app_tendenderosmart
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Ensure this is set correctly

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/sunny.png
    - assets/images/cloudy.png
